### ISSUE TITLE
Overzichtelijk code

### ISSUE THREAD

**Issue by randy554** [Mokerstier/web-app-from-scratch-1920#1]
Ik vind de structuur opbouw van de code overzichtelijk. Er staan bij alle functies duidelijke comments die de bedoeling van de functie omschrijven. Dit geldt ook voor vele variable. Ik vind de naamgeving van de variable ook heel duidelijk. De namen geven aan wat voor data ze vertegenwoordigen. Door de overzichtelijke code heb ik dingen kunnen leren die ik zelf kan toepassen in mijn eigen code.

**Comment by Mokerstier** [comment]
Thnx maat!
