### ISSUE TITLE
Actor, interaction diagram 

### ISSUE THREAD

**Issue by randy554** [Mokerstier/web-app-from-scratch-1920#12]
De actor/interaction diagram zijn vrij duidelijk te volgen. Ik ga er vanuit dat de detailpagina ongeveer hetzelfde werkt als de overviewpagina aangezien deze niet aanwezig is. Misschien kan er een aparte interaction diagram worden gemaakt voor het toevoegen van hero's aan de app.

**Comment by Mokerstier** [comment]
thnx maat
