### ISSUE TITLE
Mixed Content 🍭

### ISSUE THREAD

**Issue by robert-hoekstra** [Mokerstier/web-app-from-scratch-1920#13]
Some images are retrieved over an old HTTP request. HTTP is frowned upon by GitHub. You can fix this by changing your API or any other request to HTTPS. Should be no problem!

**Comment by Mokerstier** [comment]
Fixed! Thnx for noticing'!! 
the thing is when testing in localhost this problem didnt occur but i managed to fix it simply adding the "s" after the "http" when requesting the images.

https://github.com/Mokerstier/web-app-from-scratch-1920/blob/166c057fcf68651561e17b0e4ec68bc376502619/dev/js/modules/render.js#L5-L7

https://github.com/Mokerstier/web-app-from-scratch-1920/blob/166c057fcf68651561e17b0e4ec68bc376502619/dev/js/modules/render.js#L21-L23

This how i solved it, let me know if you think there is a cleaner solution.
