### ISSUE TITLE
Rubrik 📊

### ISSUE THREAD

**Issue by robert-hoekstra** [Mokerstier/web-app-from-scratch-1920#16]
*De code bevat geen syntaxfouten en is netjes opgemaakt: Voldoende. Let wel op de bloat van comments die je hebt.

*Code is correct gescoped en opgedeeld in modules die overeen komen met het actor diagram: Onvoldoende. Nog niet helemaal. Probeer je code meer in modules op te delen door ze uit je app.js te trekken.

*JSON data kan met een asynchrone request worden opgehaald uit een API: Goed

*JSON data kan, minimaal met de methodes; map, filter en reduce worden gemanipuleerd: Onvoldoende. Geen gebruik van map filter of reduce tegen gekomen. correct me if I am wrong.

*JSON data kan, al dan niet met een micro library, client side in de HTML worden gerenderd. Nadelen van het client-side renderen van HTML kunnen worden benoemd: Goed. Uitleg is meer voor tijdens de beoordeling. Misschien leuk voor in je documentatie?

* Routing & states kunnen, al dan niet met een micro library, worden gemanaged: onvoldoende. Kom live geen states of routing tegen.

De user flow en object / class flow zijn visueel gemaakt:

De interface bevat feedback naar de gebruiker op het moment dat er gewacht moet worden op het laden van data:

**Comment by Mokerstier** [comment]
Thnx voor de feedback ik heb alweer wat dingen uitgebreid!
